[package]
name = "media_organizer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.148"
walkdir = "2.5.0"
kamadak-exif = "0.6.1"
chrono = "0.4.42"
anyhow = "1.0.100"
